'use client';

import React from 'react'
import Head from 'next/head'
import CssBaseline from '@mui/material/CssBaseline'

export default function Template({children}: {children?: React.ReactNode} ) {
    return (
        <>
            <Head>
                <title>McMaster Branding</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CssBaseline />
            {children}
        </>
    )
}
