import {Metadata} from 'next'
import {Provider} from "@/components/Provider/Provider";
import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';

export const metadata: Metadata = {
    title: 'Modern SPA Demo',
    description: 'Generated by create next app',
    viewport: 'width=device-width, initial-scale=1',
    icons: {
        icon: '/favicon.ico',
    },
}

export function generateStaticParams() {
    return [{locale: 'en-CA'}, {locale: 'fr-CA'}];
}

export default async function RootLayout({
   // Layouts must accept a children prop.
   // This will be populated with nested layouts or pages
   children,
   params
}: {
    children: React.ReactNode,
    params: {locale: string}
}) {
    let dict
    try {
        dict = (await import(`../../dictionaries/${params.locale}.json`)).default;
    } catch (error) {
        notFound();
    }

    return (
        <NextIntlClientProvider locale={params.locale} messages={dict}>
            {children}
        </NextIntlClientProvider>
    )
}
